[2024-07-21 03:41:05,432] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2021-07-23T00:00:00+00:00 [queued]>
[2024-07-21 03:41:05,490] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2021-07-23T00:00:00+00:00 [queued]>
[2024-07-21 03:41:05,495] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,496] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-07-21 03:41:05,497] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,546] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): load_from_mysql> on 2021-07-23T00:00:00+00:00
[2024-07-21 03:41:05,560] {standard_task_runner.py:52} INFO - Started process 184 to run task
[2024-07-21 03:41:05,589] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ETL_task', 'load_from_mysql', '2021-07-23T00:00:00+00:00', '--job-id', '163', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ELT.py', '--cfg-path', '/tmp/tmp9xzi1lqm', '--error-file', '/tmp/tmp1d16_bwp']
[2024-07-21 03:41:05,592] {standard_task_runner.py:77} INFO - Job 163: Subtask load_from_mysql
[2024-07-21 03:41:51,210] {local_task_job.py:194} WARNING - Recorded pid 266 does not match the current pid 184
